// Generated by gencpp from file robopgave_pkg/Num.msg
// DO NOT EDIT!


#ifndef ROBOPGAVE_PKG_MESSAGE_NUM_H
#define ROBOPGAVE_PKG_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robopgave_pkg
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : question()
    , answer()  {
    }
  Num_(const ContainerAllocator& _alloc)
    : question(_alloc)
    , answer(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _question_type;
  _question_type question;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _answer_type;
  _answer_type answer;





  typedef boost::shared_ptr< ::robopgave_pkg::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robopgave_pkg::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::robopgave_pkg::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::robopgave_pkg::Num > NumPtr;
typedef boost::shared_ptr< ::robopgave_pkg::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robopgave_pkg::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robopgave_pkg::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robopgave_pkg::Num_<ContainerAllocator1> & lhs, const ::robopgave_pkg::Num_<ContainerAllocator2> & rhs)
{
  return lhs.question == rhs.question &&
    lhs.answer == rhs.answer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robopgave_pkg::Num_<ContainerAllocator1> & lhs, const ::robopgave_pkg::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robopgave_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robopgave_pkg::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robopgave_pkg::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robopgave_pkg::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robopgave_pkg::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robopgave_pkg::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robopgave_pkg::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robopgave_pkg::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a27d8629aeefd2b315942fe4a74ab143";
  }

  static const char* value(const ::robopgave_pkg::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa27d8629aeefd2b3ULL;
  static const uint64_t static_value2 = 0x15942fe4a74ab143ULL;
};

template<class ContainerAllocator>
struct DataType< ::robopgave_pkg::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robopgave_pkg/Num";
  }

  static const char* value(const ::robopgave_pkg::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robopgave_pkg::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string question\n"
"string answer\n"
;
  }

  static const char* value(const ::robopgave_pkg::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robopgave_pkg::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.question);
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robopgave_pkg::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robopgave_pkg::Num_<ContainerAllocator>& v)
  {
    s << indent << "question: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.question);
    s << indent << "answer: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOPGAVE_PKG_MESSAGE_NUM_H
